// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_CREATED   JobStatus = 0
	JobStatus_JOB_STATUS_PENDING   JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 3
	JobStatus_JOB_STATUS_FAILED    JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_CREATED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_CREATED":   0,
		"JOB_STATUS_PENDING":   1,
		"JOB_STATUS_RUNNING":   2,
		"JOB_STATUS_COMPLETED": 3,
		"JOB_STATUS_FAILED":    4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_models_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_models_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccessful  bool                   `protobuf:"varint,1,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

func (x *Result) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetJobQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobQuery) Reset() {
	*x = GetJobQuery{}
	mi := &file_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobQuery) ProtoMessage() {}

func (x *GetJobQuery) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobQuery.ProtoReflect.Descriptor instead.
func (*GetJobQuery) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobQuery) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccessful  bool                   `protobuf:"varint,1,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResult) Reset() {
	*x = GetJobResult{}
	mi := &file_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResult) ProtoMessage() {}

func (x *GetJobResult) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResult.ProtoReflect.Descriptor instead.
func (*GetJobResult) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobResult) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

func (x *GetJobResult) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetJobResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetJobsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccessful  bool                   `protobuf:"varint,1,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobsResult) Reset() {
	*x = GetJobsResult{}
	mi := &file_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsResult) ProtoMessage() {}

func (x *GetJobsResult) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsResult.ProtoReflect.Descriptor instead.
func (*GetJobsResult) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobsResult) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

func (x *GetJobsResult) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *GetJobsResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateJobQuery struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobType       string                  `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Context       *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobQuery) Reset() {
	*x = CreateJobQuery{}
	mi := &file_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobQuery) ProtoMessage() {}

func (x *CreateJobQuery) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobQuery.ProtoReflect.Descriptor instead.
func (*CreateJobQuery) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{4}
}

func (x *CreateJobQuery) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateJobQuery) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateJobQuery) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateJobQuery) GetContext() *wrapperspb.StringValue {
	if x != nil {
		return x.Context
	}
	return nil
}

type StartJobQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobQuery) Reset() {
	*x = StartJobQuery{}
	mi := &file_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobQuery) ProtoMessage() {}

func (x *StartJobQuery) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobQuery.ProtoReflect.Descriptor instead.
func (*StartJobQuery) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{5}
}

func (x *StartJobQuery) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CompleteJobQuery struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsFailed      bool                    `protobuf:"varint,3,opt,name=is_failed,json=isFailed,proto3" json:"is_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobQuery) Reset() {
	*x = CompleteJobQuery{}
	mi := &file_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobQuery) ProtoMessage() {}

func (x *CompleteJobQuery) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobQuery.ProtoReflect.Descriptor instead.
func (*CompleteJobQuery) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteJobQuery) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobQuery) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CompleteJobQuery) GetIsFailed() bool {
	if x != nil {
		return x.IsFailed
	}
	return false
}

type Job struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                  `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus               `protobuf:"varint,3,opt,name=status,proto3,enum=JobStatus" json:"status,omitempty"`
	Progress      int32                   `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	JobType       string                  `protobuf:"bytes,5,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Message       *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Context       *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	UserId        string                  `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{7}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_CREATED
}

func (x *Job) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Job) GetContext() *wrapperspb.StringValue {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Job) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SetProgressQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Progress      float32                `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProgressQuery) Reset() {
	*x = SetProgressQuery{}
	mi := &file_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProgressQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProgressQuery) ProtoMessage() {}

func (x *SetProgressQuery) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProgressQuery.ProtoReflect.Descriptor instead.
func (*SetProgressQuery) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{8}
}

func (x *SetProgressQuery) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SetProgressQuery) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_models_proto protoreflect.FileDescriptor

const file_models_proto_rawDesc = "" +
	"\n" +
	"\fmodels.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x06Result\x12#\n" +
	"\ris_successful\x18\x01 \x01(\bR\fisSuccessful\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"$\n" +
	"\vGetJobQuery\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"p\n" +
	"\fGetJobResult\x12#\n" +
	"\ris_successful\x18\x01 \x01(\bR\fisSuccessful\x12\x16\n" +
	"\x03job\x18\x02 \x01(\v2\x04.JobR\x03job\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"s\n" +
	"\rGetJobsResult\x12#\n" +
	"\ris_successful\x18\x01 \x01(\bR\fisSuccessful\x12\x18\n" +
	"\x04jobs\x18\x02 \x03(\v2\x04.JobR\x04jobs\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb2\x01\n" +
	"\x0eCreateJobQuery\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x126\n" +
	"\amessage\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\x126\n" +
	"\acontext\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\acontext\"&\n" +
	"\rStartJobQuery\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"~\n" +
	"\x10CompleteJobQuery\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x126\n" +
	"\amessage\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\x12\x1b\n" +
	"\tis_failed\x18\x03 \x01(\bR\bisFailed\"\x88\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\"\n" +
	"\x06status\x18\x03 \x01(\x0e2\n" +
	".JobStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x126\n" +
	"\amessage\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\amessage\x126\n" +
	"\acontext\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\acontext\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\"E\n" +
	"\x10SetProgressQuery\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x02R\bprogress*\x84\x01\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_CREATED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04B#Z!progress-tracker/api/proto/modelsb\x06proto3"

var (
	file_models_proto_rawDescOnce sync.Once
	file_models_proto_rawDescData []byte
)

func file_models_proto_rawDescGZIP() []byte {
	file_models_proto_rawDescOnce.Do(func() {
		file_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)))
	})
	return file_models_proto_rawDescData
}

var file_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_models_proto_goTypes = []any{
	(JobStatus)(0),                 // 0: JobStatus
	(*Result)(nil),                 // 1: Result
	(*GetJobQuery)(nil),            // 2: GetJobQuery
	(*GetJobResult)(nil),           // 3: GetJobResult
	(*GetJobsResult)(nil),          // 4: GetJobsResult
	(*CreateJobQuery)(nil),         // 5: CreateJobQuery
	(*StartJobQuery)(nil),          // 6: StartJobQuery
	(*CompleteJobQuery)(nil),       // 7: CompleteJobQuery
	(*Job)(nil),                    // 8: Job
	(*SetProgressQuery)(nil),       // 9: SetProgressQuery
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_models_proto_depIdxs = []int32{
	8,  // 0: GetJobResult.job:type_name -> Job
	8,  // 1: GetJobsResult.jobs:type_name -> Job
	10, // 2: CreateJobQuery.message:type_name -> google.protobuf.StringValue
	10, // 3: CreateJobQuery.context:type_name -> google.protobuf.StringValue
	10, // 4: CompleteJobQuery.message:type_name -> google.protobuf.StringValue
	0,  // 5: Job.status:type_name -> JobStatus
	10, // 6: Job.message:type_name -> google.protobuf.StringValue
	10, // 7: Job.context:type_name -> google.protobuf.StringValue
	11, // 8: Job.created_at:type_name -> google.protobuf.Timestamp
	11, // 9: Job.finished_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_models_proto_init() }
func file_models_proto_init() {
	if File_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_proto_goTypes,
		DependencyIndexes: file_models_proto_depIdxs,
		EnumInfos:         file_models_proto_enumTypes,
		MessageInfos:      file_models_proto_msgTypes,
	}.Build()
	File_models_proto = out.File
	file_models_proto_goTypes = nil
	file_models_proto_depIdxs = nil
}
